# Generated by Django 4.2 on 2025-03-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
    ]
