# Generated by Django 4.2 on 2025-03-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_admin_password_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Not Responded', 'Not Responded'), ('More Info Required', 'More Info Required')], default='Not Responded', max_length=20),
        ),
    ]
