# Generated by Django 4.2 on 2025-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_travelrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequests',
            name='employee_additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
