# Generated by Django 4.2 on 2025-03-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_travelrequests_employee_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelrequests',
            old_name='employee_additional_info',
            new_name='employee_response_to_manager',
        ),
    ]
