# Generated by Django 4.2 on 2025-03-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_rename_employee_additional_info_travelrequests_employee_response_to_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('More Info Required', 'More Info Required')], default='Pending', max_length=20),
        ),
    ]
