# Generated by Django 4.2 on 2025-03-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_alter_travelrequests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequests',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelrequests',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
