# Generated by Django 4.2 on 2025-03-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_alter_travelrequests_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequests',
            name='employee_response_to_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
