# Generated by Django 4.2 on 2025-03-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_travelrequests_employee_response_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequests',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelapp.admin'),
        ),
    ]
