# Generated by Django 4.2 on 2025-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_travelrequests_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('More Info Required', 'More Info Required'), ('Resubmitted', 'Resubmitted')], default='Pending', max_length=20),
        ),
    ]
